/* vocab-data.js — ADVANCED (C1–C2) course vocabulary.
 *
 * window.TAGALOG_VOCAB holds per-lesson review words keyed "1", "2", …,
 * plus a "titles" map of short lesson labels. Each word is
 * { tl, pron, en, cat }. This is the single source for the review grid,
 * self-check quiz, flashcards, glossary, and Anki deck — safe to hand-edit.
 *
 * Namespaced separately from the beginner and intermediate courses (its own
 * file, its own localStorage). At C1–C2 the vocabulary leans on metalanguage
 * (the Tagalog words for talking about Tagalog), deep/native register, and
 * the specialist registers of law, academia, literature, and public speech.
 */
window.TAGALOG_VOCAB = {
  "titles": {
    "1": "The Complete Focus Inventory",
    "2": "paN- Morphophonemics & Deep Derivation",
    "3": "The ay-Inversion & Marked Syntax",
    "4": "Embedding & Subordination",
    "5": "Evidentiality & Modality Gradients",
    "6": "Malalim na Tagalog",
    "7": "Academic Tagalog",
    "8": "Legal, Government & News Register",
    "9": "Rhetoric & Persuasion",
    "10": "Regional Variation",
    "11": "Literary Tagalog — Tula",
    "12": "Prose & Archaic Forms",
    "13": "Salawikain & Bugtong",
    "14": "Talinghaga — Figurative Depth",
    "15": "Translation Craft & Untranslatables",
    "16": "Editing & Style",
    "17": "Oratory — Talumpati",
    "18": "Language, Identity & Mastery"
  },

  "1": [
    { "tl": "pokus", "pron": "POH-koos", "en": "focus (the grammatical spotlight)", "cat": "Grammar terms" },
    { "tl": "tagaganap", "pron": "tah-gah-gah-NAP", "en": "actor / doer (the one who acts)", "cat": "Grammar terms" },
    { "tl": "layon", "pron": "LAH-yon", "en": "object / goal of the action", "cat": "Grammar terms" },
    { "tl": "ganapan", "pron": "gah-nah-PAN", "en": "location / place where the action happens", "cat": "Grammar terms" },
    { "tl": "tagatanggap", "pron": "tah-gah-tang-GAP", "en": "recipient", "cat": "Grammar terms" },
    { "tl": "kasangkapan", "pron": "kah-sang-KAH-pan", "en": "instrument / tool", "cat": "Grammar terms" },
    { "tl": "sanhi", "pron": "san-HEE", "en": "cause / reason", "cat": "Grammar terms" },
    { "tl": "ipanghiwa", "pron": "ee-pang-HEE-wah", "en": "to use (something) for cutting", "cat": "Instrument focus (ipang-)" },
    { "tl": "ipangsulat", "pron": "ee-pang-SOO-lat", "en": "to use (something) for writing", "cat": "Instrument focus (ipang-)" },
    { "tl": "ipambayad", "pron": "ee-pam-BAH-yad", "en": "to use (something) to pay with", "cat": "Instrument focus (ipang-)" },
    { "tl": "ipinanghiwa", "pron": "ee-pee-nang-HEE-wah", "en": "was used for cutting (completed)", "cat": "Instrument focus (ipang-)" },
    { "tl": "panghiwa", "pron": "pang-HEE-wah", "en": "a cutting implement", "cat": "Instrument nouns (pang-)" },
    { "tl": "panulat", "pron": "pah-NOO-lat", "en": "writing implement / pen", "cat": "Instrument nouns (pang-)" },
    { "tl": "pambura", "pron": "pam-BOO-rah", "en": "eraser", "cat": "Instrument nouns (pang-)" },
    { "tl": "ikinatuwa", "pron": "ee-kee-nah-too-WAH", "en": "was the cause of (someone's) delight", "cat": "Causal focus (ika-)" },
    { "tl": "ikinagalit", "pron": "ee-kee-nah-GAH-lit", "en": "was the cause of (someone's) anger", "cat": "Causal focus (ika-)" },
    { "tl": "ikinalungkot", "pron": "ee-kee-nah-LOONG-kot", "en": "was the cause of (someone's) sadness", "cat": "Causal focus (ika-)" },
    { "tl": "ikinabuhay", "pron": "ee-kee-nah-BOO-hai", "en": "was the means of (someone's) living", "cat": "Causal focus (ika-)" }
  ],

  "2": [
    { "tl": "panlapi", "pron": "pan-LAH-pee", "en": "affix", "cat": "Word-building terms" },
    { "tl": "ugat na salita", "pron": "OO-gat na sah-LEE-tah", "en": "root word", "cat": "Word-building terms" },
    { "tl": "pantig", "pron": "PAN-tig", "en": "syllable", "cat": "Word-building terms" },
    { "tl": "pagbabanghay", "pron": "pag-bah-bang-HAI", "en": "conjugation / inflection", "cat": "Word-building terms" },
    { "tl": "mamili", "pron": "mah-MEE-lee", "en": "to shop / to choose (mang- + bili)", "cat": "mang- assimilation" },
    { "tl": "mangisda", "pron": "mah-NGIS-dah", "en": "to fish (as an occupation)", "cat": "mang- assimilation" },
    { "tl": "manghiram", "pron": "mang-HEE-ram", "en": "to borrow (habitually)", "cat": "mang- assimilation" },
    { "tl": "mandurukot", "pron": "man-doo-ROO-kot", "en": "pickpocket", "cat": "mang- assimilation" },
    { "tl": "panghugas", "pron": "pang-HOO-gas", "en": "something used for washing", "cat": "pang- assimilation" },
    { "tl": "pamunas", "pron": "pah-MOO-nas", "en": "wiping cloth", "cat": "pang- assimilation" },
    { "tl": "pantahi", "pron": "pan-TAH-hee", "en": "something used for sewing", "cat": "pang- assimilation" },
    { "tl": "matandaan", "pron": "mah-tan-dah-AN", "en": "to manage to remember", "cat": "ma-…-an" },
    { "tl": "maintindihan", "pron": "mah-in-tin-DEE-han", "en": "to grasp / to be understood", "cat": "ma-…-an" },
    { "tl": "maramdaman", "pron": "mah-ram-dah-MAN", "en": "to feel / to perceive", "cat": "ma-…-an" },
    { "tl": "pakainin", "pron": "pah-kah-EE-nin", "en": "to feed (cause to eat)", "cat": "pa-…-in / pa-…-an" },
    { "tl": "painumin", "pron": "pah-ee-NOO-min", "en": "to give (someone) a drink", "cat": "pa-…-in / pa-…-an" },
    { "tl": "pahiraman", "pron": "pah-hee-RAH-man", "en": "to lend to (someone)", "cat": "pa-…-in / pa-…-an" },
    { "tl": "maging", "pron": "mah-GING", "en": "to become", "cat": "maging / magkaroon" },
    { "tl": "magkaroon", "pron": "mag-kah-roh-ON", "en": "to come to have", "cat": "maging / magkaroon" },
    { "tl": "magkasakit", "pron": "mag-kah-SAH-kit", "en": "to fall ill", "cat": "maging / magkaroon" }
  ],

  "3": [
    { "tl": "ay", "pron": "ai", "en": "inversion marker (links a fronted subject to its predicate)", "cat": "The ay construction" },
    { "tl": "karaniwang ayos", "pron": "kah-rah-NEE-wang AH-yos", "en": "usual order (predicate first)", "cat": "Sentence order" },
    { "tl": "di-karaniwang ayos", "pron": "dee kah-rah-NEE-wang AH-yos", "en": "inverted order (subject first, with ay)", "cat": "Sentence order" },
    { "tl": "panaguri", "pron": "pah-nah-goo-REE", "en": "predicate", "cat": "Sentence order" },
    { "tl": "paksa", "pron": "pak-SAH", "en": "subject / topic", "cat": "Sentence order" },
    { "tl": "Ang ginawa ko ay…", "pron": "ang gee-nah-WAH koh ai", "en": "What I did is…", "cat": "Pseudo-cleft frames" },
    { "tl": "Ang dahilan ay…", "pron": "ang dah-hee-LAN ai", "en": "The reason is…", "cat": "Pseudo-cleft frames" },
    { "tl": "Ang mahalaga ay…", "pron": "ang mah-hah-lah-GAH ai", "en": "What matters is…", "cat": "Pseudo-cleft frames" },
    { "tl": "Ang tanging…", "pron": "ang TAH-nging", "en": "The only…", "cat": "Pseudo-cleft frames" },
    { "tl": "kung kaya't", "pron": "koong kah-YAT", "en": "and so / which is why (formal)", "cat": "Formal connectors" },
    { "tl": "na siyang", "pron": "na SHAHNG", "en": "which is the one that (formal relative)", "cat": "Formal connectors" },
    { "tl": "na kung saan", "pron": "na koong sah-AN", "en": "in which / where (formal relative)", "cat": "Formal connectors" },
    { "tl": "bilang", "pron": "BEE-lang", "en": "as / in the capacity of", "cat": "Formal connectors" },
    { "tl": "ukol sa", "pron": "OO-kol sa", "en": "concerning / with respect to", "cat": "Formal connectors" },
    { "tl": "hinggil sa", "pron": "hing-GIL sa", "en": "regarding", "cat": "Formal connectors" },
    { "tl": "gayundin", "pron": "gah-yoon-DIN", "en": "likewise / also (formal)", "cat": "Formal connectors" }
  ],

  "4": [
    { "tl": "sugnay", "pron": "soog-NAI", "en": "clause", "cat": "Clause terms" },
    { "tl": "pangunahing sugnay", "pron": "pah-ngoo-NAH-hing soog-NAI", "en": "main clause", "cat": "Clause terms" },
    { "tl": "sugnay na pantulong", "pron": "soog-NAI na pan-TOO-long", "en": "subordinate clause", "cat": "Clause terms" },
    { "tl": "pangatnig", "pron": "pah-NGAT-nig", "en": "conjunction", "cat": "Clause terms" },
    { "tl": "na", "pron": "na", "en": "that (complementizer introducing a clause)", "cat": "Complementizers" },
    { "tl": "kung", "pron": "koong", "en": "whether (in reported questions)", "cat": "Complementizers" },
    { "tl": "ang katotohanang", "pron": "ang kah-toh-toh-HAH-nang", "en": "the fact that…", "cat": "Noun-phrase frames" },
    { "tl": "ang dahilan kung bakit", "pron": "ang dah-hee-LAN koong BAH-kit", "en": "the reason why…", "cat": "Noun-phrase frames" },
    { "tl": "ang posibilidad na", "pron": "ang poh-see-bee-lee-DAD na", "en": "the possibility that…", "cat": "Noun-phrase frames" },
    { "tl": "upang", "pron": "OO-pang", "en": "in order to (formal)", "cat": "Subordinators" },
    { "tl": "nang", "pron": "nang", "en": "so that / when (subordinating)", "cat": "Subordinators" },
    { "tl": "maliban kung", "pron": "mah-lee-BAN koong", "en": "unless", "cat": "Subordinators" },
    { "tl": "hangga't", "pron": "hang-GAT", "en": "as long as / until", "cat": "Subordinators" },
    { "tl": "sa halip na", "pron": "sa HAH-lip na", "en": "instead of", "cat": "Subordinators" },
    { "tl": "para bang", "pron": "PAH-rah bang", "en": "as if / as though", "cat": "Subordinators" },
    { "tl": "sa kabila ng katotohanang", "pron": "sa kah-bee-LAH nang kah-toh-toh-HAH-nang", "en": "despite the fact that…", "cat": "Subordinators" }
  ],

  "5": [
    { "tl": "tiyak", "pron": "tee-YAK", "en": "certain / sure", "cat": "Certainty scale" },
    { "tl": "walang duda", "pron": "WAH-lang DOO-dah", "en": "without doubt", "cat": "Certainty scale" },
    { "tl": "malamang", "pron": "mah-LAH-mang", "en": "likely / most probably", "cat": "Certainty scale" },
    { "tl": "marahil", "pron": "mah-RAH-hil", "en": "perhaps / probably (formal)", "cat": "Certainty scale" },
    { "tl": "tila", "pron": "TEE-lah", "en": "it seems / apparently", "cat": "Certainty scale" },
    { "tl": "wari", "pron": "WAH-ree", "en": "it seems (literary)", "cat": "Certainty scale" },
    { "tl": "waring", "pron": "WAH-ring", "en": "seemingly (before a word)", "cat": "Certainty scale" },
    { "tl": "maaaring", "pron": "mah-ah-AH-ring", "en": "may / possibly", "cat": "Certainty scale" },
    { "tl": "baka", "pron": "BAH-kah", "en": "might / I'm afraid (worried guess)", "cat": "Certainty scale" },
    { "tl": "siguro", "pron": "see-GOO-roh", "en": "probably / I guess", "cat": "Certainty scale" },
    { "tl": "yata", "pron": "YAH-tah", "en": "I think / it seems (soft hedge)", "cat": "Certainty scale" },
    { "tl": "diumano", "pron": "dee-oo-mah-NOH", "en": "allegedly / reportedly (news register)", "cat": "Source of knowledge" },
    { "tl": "ayon kay", "pron": "AH-yon kai", "en": "according to (a person)", "cat": "Source of knowledge" },
    { "tl": "ayon sa", "pron": "AH-yon sa", "en": "according to (a source)", "cat": "Source of knowledge" },
    { "tl": "anang", "pron": "AH-nang", "en": "said (literary: anang ina ko = my mother said)", "cat": "Source of knowledge" },
    { "tl": "sabi-sabi", "pron": "SAH-bee SAH-bee", "en": "rumour / hearsay", "cat": "Source of knowledge" },
    { "tl": "batay sa ulat", "pron": "BAH-tai sa OO-lat", "en": "based on the report", "cat": "Source of knowledge" },
    { "tl": "sa pagkakaalam ko", "pron": "sa pag-kah-kah-AH-lam koh", "en": "as far as I know", "cat": "Source of knowledge" }
  ],

  "6": [
    { "tl": "malalim na Tagalog", "pron": "mah-LAH-lim na tah-GAH-log", "en": "deep Tagalog (the native, unborrowed register)", "cat": "Register terms" },
    { "tl": "hiram na salita", "pron": "HEE-ram na sah-LEE-tah", "en": "loanword", "cat": "Register terms" },
    { "tl": "katutubong salita", "pron": "kah-too-TOO-bong sah-LEE-tah", "en": "native word", "cat": "Register terms" },
    { "tl": "dalamhati", "pron": "dah-lam-HAH-tee", "en": "deep sorrow / grief", "cat": "Deep words (feeling)" },
    { "tl": "hinagpis", "pron": "hee-NAG-pis", "en": "anguish / lamentation", "cat": "Deep words (feeling)" },
    { "tl": "lumbay", "pron": "loom-BAI", "en": "melancholy / loneliness", "cat": "Deep words (feeling)" },
    { "tl": "ligaya", "pron": "lee-GAH-yah", "en": "deep joy / bliss", "cat": "Deep words (feeling)" },
    { "tl": "lunggati", "pron": "loong-GAH-tee", "en": "aspiration / deep longing", "cat": "Deep words (feeling)" },
    { "tl": "diwa", "pron": "DEE-wah", "en": "spirit / essence / consciousness", "cat": "Deep words (mind & spirit)" },
    { "tl": "kaluluwa", "pron": "kah-loo-LOO-wah", "en": "soul", "cat": "Deep words (mind & spirit)" },
    { "tl": "haraya", "pron": "hah-RAH-yah", "en": "imagination (literary)", "cat": "Deep words (mind & spirit)" },
    { "tl": "guniguni", "pron": "goo-nee-GOO-nee", "en": "figment / imagining", "cat": "Deep words (mind & spirit)" },
    { "tl": "katwiran", "pron": "kat-WEE-ran", "en": "reason / rationale", "cat": "Deep words (mind & spirit)" },
    { "tl": "dangal", "pron": "DAH-ngal", "en": "honour / dignity", "cat": "Deep words (character)" },
    { "tl": "paninindigan", "pron": "pah-nee-nin-DEE-gan", "en": "conviction / the stand one takes", "cat": "Deep words (character)" },
    { "tl": "sandigan", "pron": "san-DEE-gan", "en": "pillar / that which one leans on", "cat": "Deep words (character)" },
    { "tl": "dalisay", "pron": "dah-LEE-sai", "en": "pure / unalloyed", "cat": "Deep words (quality)" },
    { "tl": "wagas", "pron": "WAH-gas", "en": "true / undying (of love, devotion)", "cat": "Deep words (quality)" },
    { "tl": "marikit", "pron": "mah-REE-kit", "en": "lovely / fair (literary)", "cat": "Deep words (quality)" }
  ],

  "7": [
    { "tl": "pananaliksik", "pron": "pah-nah-nah-LIK-sik", "en": "research", "cat": "Academic genres" },
    { "tl": "sanaysay", "pron": "sah-nai-SAI", "en": "essay", "cat": "Academic genres" },
    { "tl": "pag-aaral", "pron": "pag-AH-ah-ral", "en": "study", "cat": "Academic genres" },
    { "tl": "lagom", "pron": "LAH-gom", "en": "summary", "cat": "Academic genres" },
    { "tl": "buod", "pron": "BOO-od", "en": "abstract / synopsis", "cat": "Academic genres" },
    { "tl": "panimula", "pron": "pah-nee-MOO-lah", "en": "introduction", "cat": "Paper structure" },
    { "tl": "layunin", "pron": "lah-YOO-nin", "en": "objective / aim", "cat": "Paper structure" },
    { "tl": "metodolohiya", "pron": "meh-toh-doh-loh-HEE-yah", "en": "methodology", "cat": "Paper structure" },
    { "tl": "datos", "pron": "DAH-tos", "en": "data", "cat": "Paper structure" },
    { "tl": "pagsusuri", "pron": "pag-soo-SOO-ree", "en": "analysis", "cat": "Paper structure" },
    { "tl": "pagtalakay", "pron": "pag-tah-lah-KAI", "en": "discussion", "cat": "Paper structure" },
    { "tl": "kongklusyon", "pron": "kong-kloos-YON", "en": "conclusion", "cat": "Paper structure" },
    { "tl": "sanggunian", "pron": "sang-goo-nee-AN", "en": "references / bibliography", "cat": "Paper structure" },
    { "tl": "batay sa", "pron": "BAH-tai sa", "en": "based on", "cat": "Academic frames" },
    { "tl": "ayon sa pag-aaral", "pron": "AH-yon sa pag-AH-ah-ral", "en": "according to the study", "cat": "Academic frames" },
    { "tl": "ipinapakita ng datos na", "pron": "ee-pee-nah-pah-KEE-tah nang DAH-tos na", "en": "the data show that…", "cat": "Academic frames" },
    { "tl": "maaaring sabihin na", "pron": "mah-ah-AH-ring sah-BEE-hin na", "en": "it may be said that… (hedge)", "cat": "Academic frames" },
    { "tl": "sa madaling salita", "pron": "sa mah-dah-LING sah-LEE-tah", "en": "in short / to put it simply", "cat": "Academic frames" },
    { "tl": "tinutukoy ng", "pron": "tee-noo-too-KOI nang", "en": "…refers to (in defining)", "cat": "Academic frames" }
  ],

  "8": [
    { "tl": "batas", "pron": "bah-TAS", "en": "law", "cat": "Law & government" },
    { "tl": "saligang batas", "pron": "sah-LEE-gang bah-TAS", "en": "constitution", "cat": "Law & government" },
    { "tl": "kautusan", "pron": "kah-oo-TOO-san", "en": "order / decree", "cat": "Law & government" },
    { "tl": "resolusyon", "pron": "reh-soh-loos-YON", "en": "resolution", "cat": "Law & government" },
    { "tl": "kasunduan", "pron": "kah-soon-DOO-an", "en": "agreement / treaty", "cat": "Law & government" },
    { "tl": "karapatang pantao", "pron": "kah-rah-PAH-tang pan-TAH-oh", "en": "human rights", "cat": "Law & government" },
    { "tl": "mambabatas", "pron": "mam-bah-bah-TAS", "en": "legislator", "cat": "Law & government" },
    { "tl": "hukuman", "pron": "hoo-KOO-man", "en": "court", "cat": "The courts" },
    { "tl": "hukom", "pron": "HOO-kom", "en": "judge", "cat": "The courts" },
    { "tl": "nasasakdal", "pron": "nah-sah-sak-DAL", "en": "the accused / defendant", "cat": "The courts" },
    { "tl": "usapin", "pron": "oo-SAH-pin", "en": "case / matter at issue", "cat": "The courts" },
    { "tl": "hatol", "pron": "HAH-tol", "en": "verdict / judgement", "cat": "The courts" },
    { "tl": "pahayag", "pron": "pah-HAH-yag", "en": "statement", "cat": "News register" },
    { "tl": "ulat", "pron": "OO-lat", "en": "report", "cat": "News register" },
    { "tl": "ipinatupad", "pron": "ee-pee-nah-TOO-pad", "en": "was implemented / enforced", "cat": "News register" },
    { "tl": "isinusulong", "pron": "ee-see-noo-SOO-long", "en": "is being pushed for / advocated", "cat": "News register" },
    { "tl": "inihain", "pron": "ee-nee-HAH-in", "en": "was filed / submitted", "cat": "News register" },
    { "tl": "kinatigan", "pron": "kee-nah-TEE-gan", "en": "was upheld / sided with", "cat": "News register" }
  ],

  "9": [
    { "tl": "retorika", "pron": "reh-TOH-ree-kah", "en": "rhetoric", "cat": "Argument terms" },
    { "tl": "pangangatwiran", "pron": "pah-ngah-ngat-WEE-ran", "en": "argumentation / reasoning", "cat": "Argument terms" },
    { "tl": "patunay", "pron": "pah-TOO-nai", "en": "proof / evidence", "cat": "Argument terms" },
    { "tl": "pagtutol", "pron": "pag-TOO-tol", "en": "objection", "cat": "Argument terms" },
    { "tl": "pagpapabulaan", "pron": "pag-pah-pah-boo-lah-AN", "en": "refutation / disproving", "cat": "Argument terms" },
    { "tl": "pahayag ng paninindigan", "pron": "pah-HAH-yag nang pah-nee-nin-DEE-gan", "en": "statement of position", "cat": "Argument terms" },
    { "tl": "Bukod dito", "pron": "boo-KOD DEE-toh", "en": "Moreover / besides this", "cat": "Building the case" },
    { "tl": "Higit pa rito", "pron": "HEE-git pa REE-toh", "en": "Furthermore", "cat": "Building the case" },
    { "tl": "Sa katunayan", "pron": "sa kah-too-NAH-yan", "en": "In fact", "cat": "Building the case" },
    { "tl": "Kung gayon", "pron": "koong gah-YON", "en": "If so / therefore", "cat": "Building the case" },
    { "tl": "Sa kabuuan", "pron": "sa kah-boo-OO-an", "en": "On the whole / in sum", "cat": "Building the case" },
    { "tl": "Hindi ba't…", "pron": "hin-DEE bat", "en": "Is it not the case that…? (rhetorical)", "cat": "Rhetorical moves" },
    { "tl": "Sino ba ang…", "pron": "SEE-noh ba ang", "en": "Who indeed…? (rhetorical)", "cat": "Rhetorical moves" },
    { "tl": "Tunay ngang…", "pron": "TOO-nai ngang", "en": "It is truly the case that…", "cat": "Rhetorical moves" },
    { "tl": "Dapat nating tandaan", "pron": "DAH-pat NAH-ting tan-dah-AN", "en": "We must remember", "cat": "Rhetorical moves" },
    { "tl": "Nararapat lamang na", "pron": "nah-rah-RAH-pat LAH-mang na", "en": "It is only right that…", "cat": "Rhetorical moves" },
    { "tl": "Totoo nga na… ngunit", "pron": "toh-TOH-oh ngah na … NGOO-nit", "en": "It is true that… but (concede then refute)", "cat": "Rhetorical moves" }
  ],

  "10": [
    { "tl": "diyalekto", "pron": "dee-yah-LEK-toh", "en": "dialect", "cat": "Variation terms" },
    { "tl": "wikain", "pron": "wee-kah-IN", "en": "dialect / variety (native term)", "cat": "Variation terms" },
    { "tl": "punto", "pron": "POON-toh", "en": "accent (regional)", "cat": "Variation terms" },
    { "tl": "bigkas", "pron": "big-KAS", "en": "pronunciation", "cat": "Variation terms" },
    { "tl": "pananalita", "pron": "pah-nah-nah-LEE-tah", "en": "manner of speaking", "cat": "Variation terms" },
    { "tl": "tono", "pron": "TOH-noh", "en": "tone / intonation", "cat": "Variation terms" },
    { "tl": "pagkakaiba", "pron": "pag-kah-kah-ee-BAH", "en": "difference", "cat": "Variation terms" },
    { "tl": "taal", "pron": "tah-AL", "en": "native / genuine (of a place)", "cat": "Variation terms" },
    { "tl": "lalawigan", "pron": "lah-lah-WEE-gan", "en": "province", "cat": "Places & people" },
    { "tl": "kanayunan", "pron": "kah-nah-YOO-nan", "en": "countryside", "cat": "Places & people" },
    { "tl": "katutubong wika", "pron": "kah-too-TOO-bong WEE-kah", "en": "indigenous language", "cat": "Places & people" },
    { "tl": "ala eh", "pron": "AH-lah eh", "en": "Batangas discourse particle (softener/emphasis)", "cat": "Regional markers" },
    { "tl": "ga", "pron": "gah", "en": "Batangas variant of the question marker 'ba'", "cat": "Regional markers" },
    { "tl": "Bisaya", "pron": "bee-SAH-yah", "en": "Visayan (Cebuano and related languages)", "cat": "Other PH languages" },
    { "tl": "Ilokano", "pron": "ee-loh-KAH-noh", "en": "Ilocano", "cat": "Other PH languages" },
    { "tl": "Kapampangan", "pron": "kah-pam-PAH-ngan", "en": "Kapampangan", "cat": "Other PH languages" },
    { "tl": "Bikolano", "pron": "bee-koh-LAH-noh", "en": "Bicolano", "cat": "Other PH languages" },
    { "tl": "Waray", "pron": "WAH-rai", "en": "Waray", "cat": "Other PH languages" }
  ],

  "11": [
    { "tl": "tula", "pron": "too-LAH", "en": "poem", "cat": "Poetry terms" },
    { "tl": "panulaan", "pron": "pah-noo-lah-AN", "en": "poetry (as an art)", "cat": "Poetry terms" },
    { "tl": "makata", "pron": "mah-kah-TAH", "en": "poet", "cat": "Poetry terms" },
    { "tl": "matulain", "pron": "mah-too-lah-IN", "en": "poetic", "cat": "Poetry terms" },
    { "tl": "taludtod", "pron": "tah-lood-TOD", "en": "a line of verse", "cat": "Verse mechanics" },
    { "tl": "saknong", "pron": "sak-NONG", "en": "stanza", "cat": "Verse mechanics" },
    { "tl": "tugma", "pron": "toog-MAH", "en": "rhyme", "cat": "Verse mechanics" },
    { "tl": "sukat", "pron": "SOO-kat", "en": "metre (syllables per line)", "cat": "Verse mechanics" },
    { "tl": "malayang taludturan", "pron": "mah-LAH-yang tah-lood-TOO-ran", "en": "free verse", "cat": "Verse mechanics" },
    { "tl": "himig", "pron": "HEE-mig", "en": "melody / tone of a piece", "cat": "Verse mechanics" },
    { "tl": "awit", "pron": "AH-wit", "en": "awit — a narrative poem in 12-syllable lines", "cat": "Verse forms" },
    { "tl": "korido", "pron": "koh-REE-doh", "en": "korido — a narrative poem in 8-syllable lines", "cat": "Verse forms" },
    { "tl": "tanaga", "pron": "tah-NAH-gah", "en": "tanaga — a four-line, seven-syllable native form", "cat": "Verse forms" },
    { "tl": "dalit", "pron": "DAH-lit", "en": "dalit — a hymn or devotional verse", "cat": "Verse forms" },
    { "tl": "pasyon", "pron": "pas-YON", "en": "pasyon — the chanted verse narrative of the Passion", "cat": "Verse forms" },
    { "tl": "balagtasan", "pron": "bah-lag-TAH-san", "en": "balagtasan — a debate in verse", "cat": "Verse forms" }
  ],

  "12": [
    { "tl": "tuluyan", "pron": "too-loo-YAN", "en": "prose", "cat": "Prose terms" },
    { "tl": "nobela", "pron": "noh-BEH-lah", "en": "novel", "cat": "Prose terms" },
    { "tl": "maikling kuwento", "pron": "mah-ik-LING kwen-TOH", "en": "short story", "cat": "Prose terms" },
    { "tl": "kabanata", "pron": "kah-bah-NAH-tah", "en": "chapter", "cat": "Prose terms" },
    { "tl": "sinaunang Tagalog", "pron": "see-nah-OO-nang tah-GAH-log", "en": "old / archaic Tagalog", "cat": "Prose terms" },
    { "tl": "baybayin", "pron": "bai-BAH-yin", "en": "baybayin — the pre-colonial script", "cat": "Prose terms" },
    { "tl": "kata", "pron": "KAH-tah", "en": "we two (archaic dual pronoun; modern 'tayong dalawa')", "cat": "Archaic pronouns" },
    { "tl": "yaon", "pron": "yah-ON", "en": "that (archaic form of 'iyon')", "cat": "Archaic pronouns" },
    { "tl": "kaniya", "pron": "kan-YAH", "en": "his / her (older spelling of 'kanya')", "cat": "Archaic pronouns" },
    { "tl": "ani", "pron": "AH-nee", "en": "said (literary: ani Juan = said Juan)", "cat": "Archaic speech tags" },
    { "tl": "aniya", "pron": "ah-nee-YAH", "en": "said he / said she (literary)", "cat": "Archaic speech tags" },
    { "tl": "wika niya", "pron": "WEE-kah nee-YAH", "en": "said he / she (formal narrative)", "cat": "Archaic speech tags" },
    { "tl": "nguni't", "pron": "NGOO-nit", "en": "but (older spelling of 'ngunit')", "cat": "Archaic connectors" },
    { "tl": "datapwa't", "pron": "dah-tap-WAT", "en": "however (archaic)", "cat": "Archaic connectors" },
    { "tl": "subali't", "pron": "soo-bah-LIT", "en": "but / however (older spelling)", "cat": "Archaic connectors" },
    { "tl": "sapagka't", "pron": "sah-pag-KAT", "en": "because (formal / archaic)", "cat": "Archaic connectors" },
    { "tl": "saka't", "pron": "sah-KAT", "en": "and then / besides (archaic)", "cat": "Archaic connectors" }
  ],

  "13": [
    { "tl": "karunungang-bayan", "pron": "kah-roo-NOO-ngang BAH-yan", "en": "folk wisdom", "cat": "Folk-wisdom terms" },
    { "tl": "salawikain", "pron": "sah-lah-wee-kah-IN", "en": "proverb", "cat": "Folk-wisdom terms" },
    { "tl": "kasabihan", "pron": "kah-sah-BEE-han", "en": "saying / adage", "cat": "Folk-wisdom terms" },
    { "tl": "bugtong", "pron": "boog-TONG", "en": "riddle", "cat": "Folk-wisdom terms" },
    { "tl": "aral", "pron": "AH-ral", "en": "lesson / moral", "cat": "Folk-wisdom terms" },
    { "tl": "Kung may tiyaga, may nilaga", "pron": "koong mai tee-YAH-gah mai nee-LAH-gah", "en": "If there is perseverance, there is stew — hard work pays off", "cat": "Proverbs" },
    { "tl": "Habang may buhay, may pag-asa", "pron": "HAH-bang mai BOO-hai mai pag-AH-sah", "en": "While there is life, there is hope", "cat": "Proverbs" },
    { "tl": "Nasa Diyos ang awa, nasa tao ang gawa", "pron": "NAH-sah dee-YOS ang AH-wah NAH-sah TAH-oh ang gah-WAH", "en": "Mercy is with God, action is with people", "cat": "Proverbs" },
    { "tl": "Ang hindi lumingon sa pinanggalingan…", "pron": "ang hin-DEE loo-MEE-ngon sa pee-nang-gah-LEE-ngan", "en": "One who does not look back at where they came from will never reach their destination", "cat": "Proverbs" },
    { "tl": "Aanhin pa ang damo kung patay na ang kabayo", "pron": "ah-AN-hin pa ang DAH-moh koong pah-TAI na ang kah-BAH-yoh", "en": "What use is the grass when the horse is already dead — too late", "cat": "Proverbs" },
    { "tl": "lumingon", "pron": "loo-MEE-ngon", "en": "to look back", "cat": "Proverb vocabulary" },
    { "tl": "pinanggalingan", "pron": "pee-nang-gah-LEE-ngan", "en": "place of origin / where one came from", "cat": "Proverb vocabulary" },
    { "tl": "paroroonan", "pron": "pah-roh-roh-oh-NAN", "en": "destination / where one is going", "cat": "Proverb vocabulary" },
    { "tl": "Baston ni Adan, hindi mabilang", "pron": "BAS-ton nee AH-dan hin-DEE mah-BEE-lang", "en": "Adam's canes, beyond counting — answer: ulan (rain)", "cat": "Riddles" },
    { "tl": "Isang balong malalim, puno ng patalim", "pron": "EE-sang BAH-long mah-LAH-lim POO-noh nang pah-tah-LIM", "en": "A deep well full of blades — answer: bibig (mouth)", "cat": "Riddles" },
    { "tl": "Heto na si Kaka, bubuka-buka", "pron": "HEH-toh na see KAH-kah boo-boo-KAH boo-KAH", "en": "Here comes Kaka, opening and opening — answer: gunting (scissors)", "cat": "Riddles" },
    { "tl": "Nagtago si Pedro, labas ang ulo", "pron": "nag-TAH-goh see PED-roh LAH-bas ang OO-loh", "en": "Pedro hid but his head sticks out — answer: pako (nail)", "cat": "Riddles" },
    { "tl": "patalim", "pron": "pah-tah-LIM", "en": "blade / sharp implement", "cat": "Riddle vocabulary" }
  ],

  "14": [
    { "tl": "talinghaga", "pron": "tah-ling-HAH-gah", "en": "metaphor / deep figurative meaning", "cat": "Figure-of-speech terms" },
    { "tl": "tayutay", "pron": "tah-yoo-TAI", "en": "figure of speech", "cat": "Figure-of-speech terms" },
    { "tl": "pagtutulad", "pron": "pag-too-TOO-lad", "en": "simile (comparison with para/tulad)", "cat": "Figure-of-speech terms" },
    { "tl": "pagwawangis", "pron": "pag-wah-WAH-ngis", "en": "metaphor (direct likening)", "cat": "Figure-of-speech terms" },
    { "tl": "pagsasatao", "pron": "pag-sah-sah-TAH-oh", "en": "personification", "cat": "Figure-of-speech terms" },
    { "tl": "pagmamalabis", "pron": "pag-mah-mah-LAH-bis", "en": "hyperbole / exaggeration", "cat": "Figure-of-speech terms" },
    { "tl": "balintuna", "pron": "bah-lin-TOO-nah", "en": "irony", "cat": "Figure-of-speech terms" },
    { "tl": "pasukdol", "pron": "pah-sook-DOL", "en": "climax (rising series)", "cat": "Figure-of-speech terms" },
    { "tl": "pagpapalit-tawag", "pron": "pag-pah-pah-lit TAH-wag", "en": "metonymy (calling by an associated name)", "cat": "Figure-of-speech terms" },
    { "tl": "sagisag", "pron": "sah-GEE-sag", "en": "symbol / emblem", "cat": "Figure-of-speech terms" },
    { "tl": "pahiwatig", "pron": "pah-hee-WAH-tig", "en": "hint / implication", "cat": "Indirection" },
    { "tl": "pagpapahiwatig", "pron": "pag-pah-pah-hee-WAH-tig", "en": "the act of implying rather than stating", "cat": "Indirection" },
    { "tl": "pasaring", "pron": "pah-SAH-ring", "en": "a pointed remark aimed at someone indirectly", "cat": "Indirection" },
    { "tl": "sumakabilang-buhay", "pron": "soo-mah-kah-bee-LANG BOO-hai", "en": "to pass on / to die (euphemism)", "cat": "Euphemism" },
    { "tl": "may dinaramdam", "pron": "mai dee-nah-ram-DAM", "en": "is unwell (euphemism)", "cat": "Euphemism" },
    { "tl": "matagal nang nawawala", "pron": "mah-tah-GAL nang nah-wah-wah-LAH", "en": "has long been missing (softening)", "cat": "Euphemism" }
  ],

  "15": [
    { "tl": "pagsasalin", "pron": "pag-sah-sah-LIN", "en": "translation (the act)", "cat": "Translation terms" },
    { "tl": "salin", "pron": "SAH-lin", "en": "a translation", "cat": "Translation terms" },
    { "tl": "tagasalin", "pron": "tah-gah-SAH-lin", "en": "translator", "cat": "Translation terms" },
    { "tl": "wikang pinagmulan", "pron": "WEE-kang pee-nag-MOO-lan", "en": "source language", "cat": "Translation terms" },
    { "tl": "wikang pinagsalinan", "pron": "WEE-kang pee-nag-sah-LEE-nan", "en": "target language", "cat": "Translation terms" },
    { "tl": "literal na salin", "pron": "lee-teh-RAL na SAH-lin", "en": "literal translation", "cat": "Translation terms" },
    { "tl": "malayang salin", "pron": "mah-LAH-yang SAH-lin", "en": "free translation", "cat": "Translation terms" },
    { "tl": "katumbas", "pron": "kah-TOOM-bas", "en": "equivalent", "cat": "Translation terms" },
    { "tl": "kilig", "pron": "KEE-lig", "en": "the giddy thrill of romantic excitement", "cat": "Untranslatables" },
    { "tl": "tampo", "pron": "TAM-poh", "en": "withdrawn sulking that asks to be coaxed out", "cat": "Untranslatables" },
    { "tl": "gigil", "pron": "GEE-gil", "en": "the clenched urge to squeeze something unbearably cute", "cat": "Untranslatables" },
    { "tl": "lambing", "pron": "LAM-bing", "en": "affectionate sweetness / tenderness shown", "cat": "Untranslatables" },
    { "tl": "hiya", "pron": "hee-YAH", "en": "shame / propriety / sense of social face", "cat": "Untranslatables" },
    { "tl": "utang na loob", "pron": "OO-tang na loh-OB", "en": "a debt of gratitude that binds a relationship", "cat": "Untranslatables" },
    { "tl": "sayang", "pron": "SAH-yang", "en": "what a waste / what a shame (of a lost chance)", "cat": "Untranslatables" },
    { "tl": "bahala na", "pron": "bah-HAH-lah nah", "en": "come what may — acting despite uncertainty", "cat": "Untranslatables" },
    { "tl": "pakikiramdam", "pron": "pah-kee-kee-ram-DAM", "en": "reading a situation by feel before speaking", "cat": "Untranslatables" }
  ],

  "16": [
    { "tl": "pagwawasto", "pron": "pag-wah-WAS-toh", "en": "correction / editing", "cat": "Editing terms" },
    { "tl": "patnugot", "pron": "pat-NOO-got", "en": "editor", "cat": "Editing terms" },
    { "tl": "burador", "pron": "boo-rah-DOR", "en": "draft", "cat": "Editing terms" },
    { "tl": "kamalian", "pron": "kah-mah-lee-AN", "en": "error / mistake", "cat": "Editing terms" },
    { "tl": "wasto", "pron": "WAS-toh", "en": "correct", "cat": "Editing terms" },
    { "tl": "tumpak", "pron": "toom-PAK", "en": "accurate / exact", "cat": "Editing terms" },
    { "tl": "ng", "pron": "nang", "en": "marker: of / by (possessor, doer, object)", "cat": "ng vs nang" },
    { "tl": "nang", "pron": "nang", "en": "adverbial 'nang': when, so that, -ly", "cat": "ng vs nang" },
    { "tl": "rin", "pron": "rin", "en": "also (after a vowel or w/y)", "cat": "rin vs din" },
    { "tl": "din", "pron": "din", "en": "also (after a consonant)", "cat": "rin vs din" },
    { "tl": "bantas", "pron": "ban-TAS", "en": "punctuation", "cat": "Punctuation & spelling" },
    { "tl": "tuldok", "pron": "tool-DOK", "en": "period / full stop", "cat": "Punctuation & spelling" },
    { "tl": "kuwit", "pron": "KWIT", "en": "comma", "cat": "Punctuation & spelling" },
    { "tl": "gitling", "pron": "GIT-ling", "en": "hyphen", "cat": "Punctuation & spelling" },
    { "tl": "kudlit", "pron": "KOOD-lit", "en": "apostrophe / diacritic", "cat": "Punctuation & spelling" },
    { "tl": "panipi", "pron": "pah-NEE-pee", "en": "quotation marks", "cat": "Punctuation & spelling" },
    { "tl": "pagbaybay", "pron": "pag-bai-BAI", "en": "spelling", "cat": "Punctuation & spelling" },
    { "tl": "Ortograpiyang Pambansa", "pron": "or-toh-grah-PEE-yang pam-BAN-sah", "en": "the national orthography (the official spelling rules)", "cat": "Standards" },
    { "tl": "Komisyon sa Wikang Filipino", "pron": "koh-mees-YON sa WEE-kang fee-lee-PEE-noh", "en": "KWF — the Commission on the Filipino Language", "cat": "Standards" }
  ],

  "17": [
    { "tl": "talumpati", "pron": "tah-loom-PAH-tee", "en": "speech / oration", "cat": "Oratory terms" },
    { "tl": "mananalumpati", "pron": "mah-nah-nah-loom-PAH-tee", "en": "orator", "cat": "Oratory terms" },
    { "tl": "tagapagsalita", "pron": "tah-gah-pag-sah-LEE-tah", "en": "speaker / spokesperson", "cat": "Oratory terms" },
    { "tl": "panauhing pandangal", "pron": "pah-nah-OO-hing pan-DAH-ngal", "en": "guest of honour", "cat": "Oratory terms" },
    { "tl": "diin", "pron": "dee-IN", "en": "emphasis / stress", "cat": "Oratory terms" },
    { "tl": "tindig", "pron": "TIN-dig", "en": "bearing / stance", "cat": "Oratory terms" },
    { "tl": "pambungad", "pron": "pam-BOO-ngad", "en": "opening / introductory remarks", "cat": "Speech structure" },
    { "tl": "katawan ng talumpati", "pron": "kah-tah-WAN nang tah-loom-PAH-tee", "en": "body of the speech", "cat": "Speech structure" },
    { "tl": "pangwakas", "pron": "pang-WAH-kas", "en": "closing / conclusion", "cat": "Speech structure" },
    { "tl": "pasasalamat", "pron": "pah-sah-sah-LAH-mat", "en": "expression of thanks", "cat": "Speech structure" },
    { "tl": "parangal", "pron": "pah-RAH-ngal", "en": "tribute / honour paid", "cat": "Occasions" },
    { "tl": "pagtatapos", "pron": "pag-tah-TAH-pos", "en": "graduation / commencement", "cat": "Occasions" },
    { "tl": "pamamaalam", "pron": "pah-mah-mah-AH-lam", "en": "farewell / leave-taking", "cat": "Occasions" },
    { "tl": "Sa ngalan ng", "pron": "sa NGAH-lan nang", "en": "In the name of / on behalf of", "cat": "Set phrases" },
    { "tl": "Nais kong pasalamatan", "pron": "nah-IS kong pah-sah-lah-mah-TAN", "en": "I wish to thank…", "cat": "Set phrases" },
    { "tl": "Nais kong ibahagi", "pron": "nah-IS kong ee-bah-HAH-gee", "en": "I wish to share…", "cat": "Set phrases" },
    { "tl": "Bilang pangwakas", "pron": "BEE-lang pang-WAH-kas", "en": "In closing…", "cat": "Set phrases" },
    { "tl": "Mga minamahal kong kababayan", "pron": "mah-NGAH mee-nah-mah-HAL kong kah-bah-BAH-yan", "en": "My beloved countrymen (ceremonial address)", "cat": "Set phrases" }
  ],

  "18": [
    { "tl": "wikang pambansa", "pron": "WEE-kang pam-BAN-sah", "en": "national language", "cat": "Language policy" },
    { "tl": "wikang opisyal", "pron": "WEE-kang oh-pees-YAL", "en": "official language", "cat": "Language policy" },
    { "tl": "patakarang pangwika", "pron": "pah-tah-KAH-rang pang-WEE-kah", "en": "language policy", "cat": "Language policy" },
    { "tl": "unang wika", "pron": "OO-nang WEE-kah", "en": "first language / mother tongue", "cat": "Language policy" },
    { "tl": "pangalawang wika", "pron": "pah-ngah-LAH-wang WEE-kah", "en": "second language", "cat": "Language policy" },
    { "tl": "kababayan", "pron": "kah-bah-BAH-yan", "en": "fellow countryman", "cat": "Identity" },
    { "tl": "diaspora", "pron": "dee-yas-POH-rah", "en": "diaspora (Filipinos overseas)", "cat": "Identity" },
    { "tl": "balbal", "pron": "bal-BAL", "en": "slang (the register)", "cat": "Slang layers" },
    { "tl": "swardspeak", "pron": "SWORD-speek", "en": "swardspeak / beki — Filipino gay lingo", "cat": "Slang layers" },
    { "tl": "lodi", "pron": "LOH-dee", "en": "idol (reversed syllables)", "cat": "Slang layers" },
    { "tl": "petmalu", "pron": "pet-mah-LOO", "en": "awesome / intense (from malupit)", "cat": "Slang layers" },
    { "tl": "werpa", "pron": "WER-pah", "en": "power / strength (from 'power')", "cat": "Slang layers" },
    { "tl": "charot", "pron": "chah-ROT", "en": "just kidding", "cat": "Slang layers" },
    { "tl": "sana all", "pron": "SAH-nah ol", "en": "wish it were all of us — good-natured envy", "cat": "Slang layers" },
    { "tl": "bihasa", "pron": "bee-HAH-sah", "en": "proficient / practised", "cat": "Mastery" },
    { "tl": "dalubhasa", "pron": "dah-loob-HAH-sah", "en": "expert / specialist", "cat": "Mastery" },
    { "tl": "kasanayan", "pron": "kah-sah-NAH-yan", "en": "skill", "cat": "Mastery" },
    { "tl": "pagpapanatili", "pron": "pag-pah-pah-nah-TEE-lee", "en": "maintenance / keeping something up", "cat": "Mastery" }
  ]
};
